site_name: kosma
site_description: Una biblioteca de validaci贸n en Python, similar a la de Laravel.
site_author: Tu Nombre

repo_url: https://github.com/Stokerx/kosma
repo_name: Stokerx/kosma

nav:
    - Inicio: index.md
    - Instalaci贸n: instalacion.md
    - Uso: uso.md
    - Reglas de Validaci贸n: reglas.md
    - Personalizaci贸n: personalizacion.md
    - Contribuciones: contribuciones.md
    - Licencia: licencia.md

theme:
  name: readthedocs

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences